version: "0.2"
language: en,en-GB
useGitignore: true
words:
  - aaronmgz
  - apos
  - astrojs
  - avif
  - commitprompt
  - Coolstead
  - Contrac
  - esbuild
  - Eleventy
  - Difftale
  - frontmatter
  - fontkit
  - Hrefs
  - lock-in
  - llms
  - memudo
  - Molina
  - monorepos
  - prerendered
  - prerenders
  - ratelimits
  - referrerpolicy
  - Resvg
  - Roadscore
  - SARIF
  - santi
  - Santi
  - Satori
  - santi020k
  - Starlight
  - structured
  - subpaths
  - nosniff
  - viewbox
  - worktree
  - WebP
  - wght
ignorePaths:
  - .wrangler/**
  - apps/web/.wrangler/**
  - .astro/**
  - .turbo/**
  - coverage/**
  - dist/**
  - node_modules/**
  - pnpm-lock.yaml
