version: "0.2"
language: en,en-GB
useGitignore: true
words:
  - avif
  - commitprompt
  - Contrac
  - esbuild
  - frontmatter
  - fontkit
  - lock-in
  - Molina
  - monorepos
  - Resvg
  - santi
  - Santi
  - Satori
  - santi020k
  - Starlight
  - structured
  - WebP
  - wght
ignorePaths:
  - .astro/**
  - .turbo/**
  - coverage/**
  - dist/**
  - node_modules/**
  - pnpm-lock.yaml
