version: "0.2"
language: en,en-GB
useGitignore: true
words:
  - apos
  - astrojs
  - avif
  - commitprompt
  - Contrac
  - esbuild
  - Eleventy
  - frontmatter
  - fontkit
  - Hrefs
  - lock-in
  - Molina
  - monorepos
  - Resvg
  - SARIF
  - santi
  - Santi
  - Satori
  - santi020k
  - Starlight
  - structured
  - WebP
  - wght
ignorePaths:
  - .astro/**
  - .turbo/**
  - coverage/**
  - dist/**
  - node_modules/**
  - pnpm-lock.yaml
